### ISSUE TITLE
Insert text/custom component into center?

### ISSUE THREAD

**Issue by JackZheng10** [tomma5o/react-score-indicator#9]
Hey, great component. Was wondering if it was possible to insert a custom component (like Typography from Material-UI) or text in the center.

Hacky solutions are welcome - I've just imported the component into a file anyways. (Although importing the src/ files results in the score being formatted incorrectly. Using the dist/index.js file worked.)

Thanks!

**Comment by JackZheng10** [comment]
Nevermind! (I think) I've managed a solution with the following code:
```
  <CardContent
              style={{
                display: "flex",
                justifyContent: "center",
              }}
            >
              <ReactScoreIndicator
                value={30}
                maxValue={100}
                width={300}
                lineGap={0}
                lineWidth={15}
                fadedOpacity={20}
                stepsColors={doughnutColors}
              />
              <div
                style={{
                  position: "relative",
                }}
              >
                <div
                  style={{
                    top: 170,
                    left: -245,
                    position: "absolute",
                  }}
                >
                  <Typography variant="h3">test</Typography>
                </div>
              </div>
            </CardContent>
```

![image](https://user-images.githubusercontent.com/44103100/83706290-195f6f00-a5e5-11ea-91ba-2126fc754a36.png)

For anyone else, you'll probably need to play around with the top and left properties. Also, CardContent is from the Material-UI library. Was not able to get it working without it.

**Comment by tomma5o** [comment]
Hi @JackZheng10, I think the solution you've found is the fastest one 👍 
Thanks for reporting the solution 🙏 

I'll close this and I open a feature for better manage the text inside a component this week!
